spring:
  application:
    name: "auth-service"

server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

JWT_SECRET: a3f12e6c8b4d97e1f68e2a3e0f8b5d8e1c7a2f3d5c8e1b3f7a1d2c3e4f5b6a7c