services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - auth-service
      - flight-service
      - airport-service
      - user-service
      - schedule-service
      - payment-service
      - booking-service

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  airport-service:
    build:
      context: ./airport-service
    container_name: airport-service
    ports:
      - "9001:9001"
    depends_on:
      - eureka-server
      - mysql
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  flight-service:
    build:
      context: ./flight-service
    container_name: flight-service
    ports:
      - "9003:9003"
    depends_on:
      - eureka-server
      - mongodb
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  schedule-service:
    build:
      context: ./schedule-service
    container_name: schedule-service
    ports:
      - "9004:9004"
    depends_on:
      - eureka-server
      - mongodb
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  booking-service:
    build:
      context: ./booking-service
    container_name: booking-service
    ports:
      - "9006:9006"
    depends_on:
      - eureka-server
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "9005:9005"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  onboard-app:
    image: aadityarmall/aviation-ticketing-system:on-board-latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_RAZORPAY_KEY_ID = rzp_test_x0joxYG34sLh5M
      - NEXT_PUBLIC_API_URL = http://api-gateway:8080

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
  default:
    name: flight-booking-network
    driver: bridge

volumes:
  mysql-data:
  mongo-data:
  rabbitmq-data:
