server:
  port: 9003
spring:
  application:
    name: "flight-service"
  data:
    mongodb:
      uri: "mongodb+srv://shivam:haZUTQy7X8JxJGsu@ticketing-system.btfz7.mongodb.net/?retryWrites=true&w=majority&appName=Ticketing-System"
      database: "ticketing-system"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/