server:
  port: 9003
spring:
  application:
    name: "flight-service"
  data:
    mongodb:
      uri: "mongodb://localhost:27017/flight-service"
      database: "flight-service"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/