spring:
  data:
    mongodb:
      uri: "mongodb://mongodb:27017/flight-service"
      database: "flight-service"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
