server:
  port: 9003
spring:
  application:
    name: "flight-service"
  datasource:
    url: jdbc:mysql://localhost:3306/flight-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/