server:
  port: 9003
spring:
  application:
    name: "flight-service"
  data:
    mongodb:
      uri: "mongodb://localhost:27017/flight-service"
      database: "flight-service"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}