spring:
  data:
    mongodb:
      uri: "mongodb://mongodb:27017/booking-service"
      database: "booking-service"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
