spring:
  application:
    name: "payment-service"
server:
  port: 9006

razorpay:
  api:
    key: "rzp_test_x0joxYG34sLh5M"
    secret: "3xRd6oiHPPXELe8DrGB7IADj"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}