spring:
  application:
    name: "schedule-service"
  data:
    mongodb:
      uri: "mongodb://localhost:27017/schedule-service"
      database: "schedule-service"
server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}