spring:
  application:
    name: "user-service"
  datasource:
    url: "jdbc:mysql://localhost:3306/ticketing-system"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
server:
  port: 9000


