spring:
  application:
    name: "user-service"
  datasource:
    url: "jdbc:mysql://localhost:3306/user-service"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
