spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/airport-service"
    username: "root"
    password: "root"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
