spring:
  application:
    name: "airport-service"
  datasource:
    url: "jdbc:mysql://localhost:3306/airport-service"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
server:
  port: 9001
