spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/airport-service"
    username: "root"
    password: "root"
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
